export const es = {
    buttons: { left: 'Izquierdo', middle: 'Central', right: 'Derecho' },
    total: 'Total',
    interval: 'Intervalo',
    lastButton: 'Último botón',
    ready: 'Listo para probar',
    readyDesc: 'Haz clic en el área de arriba con cualquier botón del ratón.',
    clickedWith: 'Clic con el botón {btn}',
    firstClick: 'Primer clic registrado.',
    sinceLast: '{diff} desde el clic anterior.',
    reset: 'Reiniciar',
    clearLog: 'Limpiar registro',
    historyHeading: 'Historial',
    historyEmpty: 'Aún no hay resultados guardados.',
    logTitle: 'Registro de eventos',
    logSubtitle: 'Los eventos más recientes aparecen primero',
    noRecords: 'Ningún evento registrado.',
    colId: 'Nº',
    colButton: 'Botón',
    colInterval: 'Intervalo',
    colTime: 'Hora',
    threshold: 'Umbral',
    suspects: 'Sospechosos',
    doubleDetected: 'Doble clic detectado',
    doubleDetectedDesc: 'Dos clics en {diff} — por debajo del umbral de {threshold}.',
    doubleClean: 'Clic único registrado',
    doubleCleanDesc: 'Intervalo de {diff}. Sigue haciendo clic despacio.',
    verdictClean: 'Ninguna repetición sospechosa hasta ahora.',
    verdictSuspect: '{count} repetición(es) por debajo del umbral. Eso indica un switch desgastado.',
    duration: 'Duración',
    seconds: 's',
    clicks: 'Clics',
    timeLeft: 'Restante',
    cps: 'CPS',
    cpsReady: 'Haz clic para empezar',
    cpsReadyDesc: 'El cronómetro arranca con tu primer clic.',
    cpsRunning: '¡Ahora!',
    cpsRunningDesc: 'Haz clic lo más rápido que puedas.',
    cpsDone: 'Resultado: {cps} CPS',
    cpsDoneDesc: '{clicks} clics en {duration}s.',
    best: 'Mejor',
    steps: 'Pasos',
    direction: 'Dirección',
    reversals: 'Inversiones',
    up: 'Arriba',
    down: 'Abajo',
    left_: 'Izquierda',
    right_: 'Derecha',
    scrollReady: 'Gira la rueda del ratón',
    scrollReadyDesc: 'Usa la rueda dentro de esta área, en ambos sentidos.',
    scrollActive: 'Desplazando hacia {dir}',
    scrollActiveDesc: '{steps} pasos registrados.',
    reversalWarn: 'Inversión detectada: la dirección cambió sin que tú la cambiaras.',
    estimated: 'Estimación',
    samples: 'Muestras',
    avgInterval: 'Intervalo medio',
    pollingReady: 'Mueve el ratón',
    pollingReadyDesc: 'Haz movimientos amplios y continuos durante unos segundos.',
    pollingUnsupported: 'La lectura se quedó en torno a 60 Hz, que es el techo de entrega de eventos de este navegador, no la tasa de tu ratón. Ningún ratón reporta a 60 Hz: la más baja en uso es 125. Firefox y sus derivados limitan la entrega a unas 60 veces por segundo y no exponen las muestras intermedias, sea cual sea el monitor. Para medir la tasa real, abre esta página en Chrome, Edge u Opera.',
    pollingMeasuring: 'Midiendo...',
    pollingMeasuringDesc: '{samples} muestras recogidas. Sigue moviendo.',
    pollingDone: 'Aproximadamente {hz} Hz',
    pollingDoneDesc: 'Basado en {samples} muestras, intervalo medio de {ms} ms.',
    measure: 'Medir de nuevo',
};

export const fr = {
    buttons: { left: 'Gauche', middle: 'Milieu', right: 'Droit' },
    total: 'Total',
    interval: 'Intervalle',
    lastButton: 'Dernier bouton',
    ready: 'Prêt à tester',
    readyDesc: 'Cliquez dans la zone ci-dessus avec n’importe quel bouton de la souris.',
    clickedWith: 'Clic avec le bouton {btn}',
    firstClick: 'Premier clic enregistré.',
    sinceLast: '{diff} depuis le clic précédent.',
    reset: 'Réinitialiser',
    clearLog: 'Effacer le journal',
    historyHeading: 'Historique',
    historyEmpty: 'Aucun résultat enregistré pour l’instant.',
    logTitle: 'Journal des événements',
    logSubtitle: 'Les événements les plus récents en premier',
    noRecords: 'Aucun événement enregistré.',
    colId: 'Nº',
    colButton: 'Bouton',
    colInterval: 'Intervalle',
    colTime: 'Heure',
    threshold: 'Seuil',
    suspects: 'Suspects',
    doubleDetected: 'Double clic détecté',
    doubleDetectedDesc: 'Deux clics en {diff} — sous le seuil de {threshold}.',
    doubleClean: 'Clic unique enregistré',
    doubleCleanDesc: 'Intervalle de {diff}. Continuez à cliquer lentement.',
    verdictClean: 'Aucune répétition suspecte pour le moment.',
    verdictSuspect: '{count} répétition(s) sous le seuil. Cela indique un switch usé.',
    duration: 'Durée',
    seconds: 's',
    clicks: 'Clics',
    timeLeft: 'Restant',
    cps: 'CPS',
    cpsReady: 'Cliquez pour commencer',
    cpsReadyDesc: 'Le chronomètre démarre à votre premier clic.',
    cpsRunning: 'C’est parti !',
    cpsRunningDesc: 'Cliquez aussi vite que possible.',
    cpsDone: 'Résultat : {cps} CPS',
    cpsDoneDesc: '{clicks} clics en {duration}s.',
    best: 'Meilleur',
    steps: 'Crans',
    direction: 'Direction',
    reversals: 'Inversions',
    up: 'Haut',
    down: 'Bas',
    left_: 'Gauche',
    right_: 'Droite',
    scrollReady: 'Faites tourner la molette',
    scrollReadyDesc: 'Utilisez la molette dans cette zone, dans les deux sens.',
    scrollActive: 'Défilement vers {dir}',
    scrollActiveDesc: '{steps} crans enregistrés.',
    reversalWarn: 'Inversion détectée : la direction a changé sans action de votre part.',
    estimated: 'Estimation',
    samples: 'Échantillons',
    avgInterval: 'Intervalle moyen',
    pollingReady: 'Bougez la souris',
    pollingReadyDesc: 'Faites des mouvements amples et continus pendant quelques secondes.',
    pollingUnsupported: 'La lecture est restée autour de 60 Hz, ce qui correspond au plafond de livraison d’événements de ce navigateur et non à la fréquence de votre souris. Aucune souris ne rapporte à 60 Hz : la plus lente en usage est à 125. Firefox et ses dérivés limitent la livraison à environ 60 fois par seconde et n’exposent pas les échantillons intermédiaires, quel que soit l’écran. Pour mesurer la fréquence réelle, ouvrez cette page dans Chrome, Edge ou Opera.',
    pollingMeasuring: 'Mesure en cours...',
    pollingMeasuringDesc: '{samples} échantillons collectés. Continuez à bouger.',
    pollingDone: 'Environ {hz} Hz',
    pollingDoneDesc: 'Basé sur {samples} échantillons, intervalle moyen de {ms} ms.',
    measure: 'Mesurer à nouveau',
};

export const de = {
    buttons: { left: 'Links', middle: 'Mitte', right: 'Rechts' },
    total: 'Gesamt',
    interval: 'Intervall',
    lastButton: 'Letzte Taste',
    ready: 'Bereit zum Testen',
    readyDesc: 'Klicke oben in den Bereich mit einer beliebigen Maustaste.',
    clickedWith: 'Klick mit der Taste {btn}',
    firstClick: 'Erster Klick erfasst.',
    sinceLast: '{diff} seit dem vorherigen Klick.',
    reset: 'Zurücksetzen',
    clearLog: 'Protokoll leeren',
    historyHeading: 'Verlauf',
    historyEmpty: 'Noch keine gespeicherten Ergebnisse.',
    logTitle: 'Ereignisprotokoll',
    logSubtitle: 'Neueste Ereignisse zuerst',
    noRecords: 'Keine Ereignisse erfasst.',
    colId: 'Nr.',
    colButton: 'Taste',
    colInterval: 'Intervall',
    colTime: 'Uhrzeit',
    threshold: 'Schwelle',
    suspects: 'Verdächtige',
    doubleDetected: 'Doppelklick erkannt',
    doubleDetectedDesc: 'Zwei Klicks in {diff} — unter der Schwelle von {threshold}.',
    doubleClean: 'Einzelklick erfasst',
    doubleCleanDesc: 'Intervall von {diff}. Klicke weiter langsam.',
    verdictClean: 'Bisher keine verdächtigen Wiederholungen.',
    verdictSuspect: '{count} Wiederholung(en) unter der Schwelle. Das deutet auf einen verschlissenen Switch hin.',
    duration: 'Dauer',
    seconds: 's',
    clicks: 'Klicks',
    timeLeft: 'Verbleibend',
    cps: 'CPS',
    cpsReady: 'Klicken zum Starten',
    cpsReadyDesc: 'Die Stoppuhr startet mit deinem ersten Klick.',
    cpsRunning: 'Los!',
    cpsRunningDesc: 'Klicke so schnell du kannst.',
    cpsDone: 'Ergebnis: {cps} CPS',
    cpsDoneDesc: '{clicks} Klicks in {duration}s.',
    best: 'Bestwert',
    steps: 'Rastungen',
    direction: 'Richtung',
    reversals: 'Umkehrungen',
    up: 'Oben',
    down: 'Unten',
    left_: 'Links',
    right_: 'Rechts',
    scrollReady: 'Drehe das Mausrad',
    scrollReadyDesc: 'Nutze das Rad in diesem Bereich, in beide Richtungen.',
    scrollActive: 'Scrollen nach {dir}',
    scrollActiveDesc: '{steps} Rastungen erfasst.',
    reversalWarn: 'Umkehrung erkannt: Die Richtung wechselte ohne dein Zutun.',
    estimated: 'Schätzung',
    samples: 'Messwerte',
    avgInterval: 'Mittleres Intervall',
    pollingReady: 'Bewege die Maus',
    pollingReadyDesc: 'Mache einige Sekunden lang weite, durchgehende Bewegungen.',
    pollingUnsupported: 'Die Messung blieb bei rund 60 Hz stehen — das ist die Obergrenze der Ereignisauslieferung dieses Browsers, nicht die Rate deiner Maus. Keine Maus meldet mit 60 Hz: die niedrigste gebräuchliche Rate ist 125. Firefox und seine Ableger liefern etwa 60 Mal pro Sekunde aus und geben die Zwischenwerte nicht preis, unabhängig vom Monitor. Für die echte Rate öffne diese Seite in Chrome, Edge oder Opera.',
    pollingMeasuring: 'Messung läuft...',
    pollingMeasuringDesc: '{samples} Messwerte gesammelt. Bewege weiter.',
    pollingDone: 'Etwa {hz} Hz',
    pollingDoneDesc: 'Basierend auf {samples} Messwerten, mittleres Intervall {ms} ms.',
    measure: 'Erneut messen',
};

export const it = {
    buttons: { left: 'Sinistro', middle: 'Centrale', right: 'Destro' },
    total: 'Totale',
    interval: 'Intervallo',
    lastButton: 'Ultimo tasto',
    ready: 'Pronto per il test',
    readyDesc: 'Clicca nell’area qui sopra con un tasto qualsiasi del mouse.',
    clickedWith: 'Clic con il tasto {btn}',
    firstClick: 'Primo clic registrato.',
    sinceLast: '{diff} dal clic precedente.',
    reset: 'Reimposta',
    clearLog: 'Svuota il registro',
    historyHeading: 'Cronologia',
    historyEmpty: 'Nessun risultato salvato finora.',
    logTitle: 'Registro eventi',
    logSubtitle: 'Gli eventi più recenti compaiono per primi',
    noRecords: 'Nessun evento registrato.',
    colId: 'N.',
    colButton: 'Tasto',
    colInterval: 'Intervallo',
    colTime: 'Ora',
    threshold: 'Soglia',
    suspects: 'Sospetti',
    doubleDetected: 'Doppio clic rilevato',
    doubleDetectedDesc: 'Due clic in {diff} — sotto la soglia di {threshold}.',
    doubleClean: 'Clic singolo registrato',
    doubleCleanDesc: 'Intervallo di {diff}. Continua a cliccare lentamente.',
    verdictClean: 'Nessuna ripetizione sospetta finora.',
    verdictSuspect: '{count} ripetizione/i sotto la soglia. Indica uno switch usurato.',
    duration: 'Durata',
    seconds: 's',
    clicks: 'Clic',
    timeLeft: 'Restante',
    cps: 'CPS',
    cpsReady: 'Clicca per iniziare',
    cpsReadyDesc: 'Il cronometro parte dal tuo primo clic.',
    cpsRunning: 'Via!',
    cpsRunningDesc: 'Clicca il più velocemente possibile.',
    cpsDone: 'Risultato: {cps} CPS',
    cpsDoneDesc: '{clicks} clic in {duration}s.',
    best: 'Migliore',
    steps: 'Scatti',
    direction: 'Direzione',
    reversals: 'Inversioni',
    up: 'Su',
    down: 'Giù',
    left_: 'Sinistra',
    right_: 'Destra',
    scrollReady: 'Gira la rotellina',
    scrollReadyDesc: 'Usa la rotellina in quest’area, in entrambi i versi.',
    scrollActive: 'Scorrimento verso {dir}',
    scrollActiveDesc: '{steps} scatti registrati.',
    reversalWarn: 'Inversione rilevata: la direzione è cambiata senza che tu la cambiassi.',
    estimated: 'Stima',
    samples: 'Campioni',
    avgInterval: 'Intervallo medio',
    pollingReady: 'Muovi il mouse',
    pollingReadyDesc: 'Fai movimenti ampi e continui per qualche secondo.',
    pollingUnsupported: 'La lettura si è fermata intorno ai 60 Hz, che è il tetto di consegna degli eventi di questo browser, non la frequenza del tuo mouse. Nessun mouse riporta a 60 Hz: la più bassa in uso è 125. Firefox e i suoi derivati limitano la consegna a circa 60 volte al secondo e non espongono i campioni intermedi, qualunque sia il monitor. Per misurare la frequenza reale, apri questa pagina in Chrome, Edge o Opera.',
    pollingMeasuring: 'Misurazione in corso...',
    pollingMeasuringDesc: '{samples} campioni raccolti. Continua a muovere.',
    pollingDone: 'Circa {hz} Hz',
    pollingDoneDesc: 'Basato su {samples} campioni, intervallo medio di {ms} ms.',
    measure: 'Misura di nuovo',
};
