/** Textos dos widgets. A cópia de SEO fica em content/mouse; aqui só rótulos de interface. */
export const widgetStrings = {
    pt: {
        buttons: { left: 'Esquerdo', middle: 'Meio', right: 'Direito' },
        total: 'Total',
        interval: 'Intervalo',
        lastButton: 'Último botão',
        ready: 'Pronto para testar',
        readyDesc: 'Clique na área acima com qualquer botão do mouse.',
        clickedWith: 'Clique com o botão {btn}',
        firstClick: 'Primeiro clique registrado.',
        sinceLast: '{diff} desde o clique anterior.',
        reset: 'Reiniciar',
        clearLog: 'Limpar registro',
        historyHeading: 'Histórico',
        historyEmpty: 'Nenhum resultado salvo ainda.',
        logTitle: 'Registro de eventos',
        logSubtitle: 'Os eventos mais recentes aparecem primeiro',
        noRecords: 'Nenhum evento registrado.',
        colId: 'Nº',
        colButton: 'Botão',
        colInterval: 'Intervalo',
        colTime: 'Horário',
        // Double click
        threshold: 'Limiar',
        suspects: 'Suspeitos',
        doubleDetected: 'Clique duplo detectado',
        doubleDetectedDesc: 'Dois cliques em {diff} — abaixo do limiar de {threshold}.',
        doubleClean: 'Clique único registrado',
        doubleCleanDesc: 'Intervalo de {diff}. Continue clicando devagar.',
        verdictClean: 'Nenhuma repetição suspeita até agora.',
        verdictSuspect: '{count} repetição(ões) abaixo do limiar. Isso indica switch com desgaste.',
        // CPS
        duration: 'Duração',
        seconds: 's',
        clicks: 'Cliques',
        timeLeft: 'Restante',
        cps: 'CPS',
        cpsReady: 'Clique para começar',
        cpsReadyDesc: 'O cronômetro parte do seu primeiro clique.',
        cpsRunning: 'Valendo!',
        cpsRunningDesc: 'Clique o mais rápido que conseguir.',
        cpsDone: 'Resultado: {cps} CPS',
        cpsDoneDesc: '{clicks} cliques em {duration}s.',
        best: 'Melhor',
        // Scroll
        steps: 'Passos',
        direction: 'Direção',
        reversals: 'Inversões',
        up: 'Cima',
        down: 'Baixo',
        left_: 'Esquerda',
        right_: 'Direita',
        scrollReady: 'Role a roda do mouse',
        scrollReadyDesc: 'Use a roda dentro desta área, nos dois sentidos.',
        scrollActive: 'Rolando para {dir}',
        scrollActiveDesc: '{steps} passos registrados.',
        reversalWarn: 'Inversão detectada: a direção mudou sem você mudar o sentido.',
        // Polling rate
        estimated: 'Estimativa',
        samples: 'Amostras',
        avgInterval: 'Intervalo médio',
        pollingReady: 'Mova o mouse',
        pollingReadyDesc: 'Movimento contínuo por alguns segundos dá a melhor leitura.',
        pollingMeasuring: 'Medindo...',
        pollingMeasuringDesc: '{samples} amostras coletadas. Continue movendo.',
        pollingDone: 'Aproximadamente {hz} Hz',
        pollingDoneDesc: 'Baseado em {samples} amostras, intervalo médio de {ms} ms.',
        measure: 'Medir novamente',
    },
    en: {
        buttons: { left: 'Left', middle: 'Middle', right: 'Right' },
        total: 'Total',
        interval: 'Interval',
        lastButton: 'Last button',
        ready: 'Ready to test',
        readyDesc: 'Click the area above with any mouse button.',
        clickedWith: 'Clicked with the {btn} button',
        firstClick: 'First click recorded.',
        sinceLast: '{diff} since the previous click.',
        reset: 'Reset',
        clearLog: 'Clear log',
        historyHeading: 'History',
        historyEmpty: 'No saved results yet.',
        logTitle: 'Event log',
        logSubtitle: 'Most recent events first',
        noRecords: 'No events recorded.',
        colId: '#',
        colButton: 'Button',
        colInterval: 'Interval',
        colTime: 'Time',
        threshold: 'Threshold',
        suspects: 'Suspects',
        doubleDetected: 'Double click detected',
        doubleDetectedDesc: 'Two clicks in {diff} — below the {threshold} threshold.',
        doubleClean: 'Single click recorded',
        doubleCleanDesc: 'Interval of {diff}. Keep clicking slowly.',
        verdictClean: 'No suspicious repeats so far.',
        verdictSuspect: '{count} repeat(s) below the threshold. That points to a worn switch.',
        duration: 'Duration',
        seconds: 's',
        clicks: 'Clicks',
        timeLeft: 'Left',
        cps: 'CPS',
        cpsReady: 'Click to start',
        cpsReadyDesc: 'The timer starts on your first click.',
        cpsRunning: 'Go!',
        cpsRunningDesc: 'Click as fast as you can.',
        cpsDone: 'Result: {cps} CPS',
        cpsDoneDesc: '{clicks} clicks in {duration}s.',
        best: 'Best',
        steps: 'Steps',
        direction: 'Direction',
        reversals: 'Reversals',
        up: 'Up',
        down: 'Down',
        left_: 'Left',
        right_: 'Right',
        scrollReady: 'Scroll the wheel',
        scrollReadyDesc: 'Use the wheel inside this area, in both directions.',
        scrollActive: 'Scrolling {dir}',
        scrollActiveDesc: '{steps} steps recorded.',
        reversalWarn: 'Reversal detected: direction flipped without you changing it.',
        estimated: 'Estimate',
        samples: 'Samples',
        avgInterval: 'Average interval',
        pollingReady: 'Move the mouse',
        pollingReadyDesc: 'Continuous movement for a few seconds gives the best reading.',
        pollingMeasuring: 'Measuring...',
        pollingMeasuringDesc: '{samples} samples collected. Keep moving.',
        pollingDone: 'Approximately {hz} Hz',
        pollingDoneDesc: 'Based on {samples} samples, average interval of {ms} ms.',
        measure: 'Measure again',
    },
};

export const getWidgetStrings = (locale) => widgetStrings[locale] || widgetStrings.pt;

export const fill = (template, values) => (
    Object.entries(values).reduce(
        (text, [key, value]) => text.replaceAll(`{${key}}`, value),
        template || ''
    )
);
